"""initial schema

Revision ID: a0c3247c5b68
Revises: 
Create Date: 2026-06-15 14:12:42.210721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



revision: str = 'a0c3247c5b68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
